# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 468de6d232277367f565b1e3e63c2c3b8abde56a98611c9fdc1bb2e04b1bf1be8fa6dd30281d63ab5a23063d87cbc45e4a8b13d2ea66c81cf71b362b3d3ba5c0

test:
  secret_key_base: 9da5fbaac866c3df32dc46193ef54d8110957f5c563feba3d619427395da69d9d3f1552417f0784f7d10f609d1955d76cda98e751b3b7cc4be37977505530c38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
